### ISSUE TITLE
Font icons can't be safely used inside CSS

### ISSUE THREAD

**Issue by jbalsas** [liferay/alloy-editor#145]
Currently, alloyeditor is generating an alloyeditor icon font with all the available icons.

The usual way to use them is from markup (html), using the generated classes such as:
```html
<span class="alloy-editor-icon-bold"></span>
```

Another way to use them is from css. For that, we access the glyph directly such as:
```css
.alloy-editor-twitter-link {
    &:after {
        content: '\E018';
        font-family: alloyeditor;
    }
}
```

The problem is that whenever a new svg is added, the generated font changes and the glyphs do not stay fixed, so the content may change from time to time. It would be great if we could safely use them from a map generated in build-time lik:

```css
.alloy-editor-twitter-link {
    &:after {
        content: map_get(alloyeditoricons, twitter);
        font-family: alloyeditor;
    }
}
```
