### ISSUE TITLE
Content override

### ISSUE THREAD

**Issue by akaiworld** [liferay/alloy-editor#342]
When limited in space (right or left) toolbars buttons go to the "next line" and so it gets over the text in the inline mode. On the screenshot the is an iframe end to the right of the toolbar. Text selected is beneath the toolbar
<img width="782" alt="2015-09-12 19 07 54" src="https://cloud.githubusercontent.com/assets/1163876/9832139/92abbc0a-5979-11e5-8b62-1edc1ed04544.png">

**Comment by ipeychev** [comment]
A simple fix might be to set some additional style to the toolbar, for example:
```css
.ae-toolbar-styles {
    min-width: 500px; // set as much as you want, this depends on the number of icons you added to the toolbar
}
```
